Repository goorm-8bit/moyeohaeng-backend, pull requests merged in 2025-08, with the labels that each got.

#4 [CI] 빌드/테스트 워크플로우 설정
  .github/workflows/build-and-test.yml
  build.gradle
Labels: 📦 ci/cd

#6 doc: CODING_STANDARDS.md 추가
  CODING_STANDARDS.md
Labels: 📝 docs

#8 [doc] coderabbit.yaml 문서 추가
  .coderabbit.yaml
Labels: 📝 docs

#12 [FEATURE] BaseEntity 구현
  src/main/java/eightbit/moyeohaeng/MoyeohaengApplication.java
  src/main/java/eightbit/moyeohaeng/global/config/JpaAuditingConfig.java
  src/main/java/eightbit/moyeohaeng/global/domain/BaseEntity.java
Labels: ✨ feature

#19 [TEST] Testcontainers 설정
  build.gradle
  compose.yml
  src/test/java/eightbit/moyeohaeng/MoyeohaengApplicationTests.java
  src/test/java/eightbit/moyeohaeng/support/annotation/IntegrationTest.java
  src/test/java/eightbit/moyeohaeng/support/container/TestContainers.java
  src/test/java/eightbit/moyeohaeng/support/util/JsonUtils.java
Labels: ✅ test

#24 [FEATURE] 회원가입
  build.gradle
  compose.yml
  src/main/java/eightbit/moyeohaeng/MoyeohaengApplication.java
  src/main/java/eightbit/moyeohaeng/domain/auth/controller/AuthController.java
  src/main/java/eightbit/moyeohaeng/domain/auth/dto/SignUpRequest.java
  src/main/java/eightbit/moyeohaeng/domain/auth/exception/AuthErrorCode.java
  src/main/java/eightbit/moyeohaeng/domain/auth/exception/AuthException.java
  src/main/java/eightbit/moyeohaeng/domain/auth/service/AuthService.java
  src/main/java/eightbit/moyeohaeng/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/eightbit/moyeohaeng/domain/member/entity/member/Member.java
  src/main/java/eightbit/moyeohaeng/domain/member/service/MemberService.java
  src/main/java/eightbit/moyeohaeng/global/config/CorsConfig.java
  src/main/java/eightbit/moyeohaeng/global/config/SecurityConfig.java
  src/main/java/eightbit/moyeohaeng/global/exception/handler/GlobalExceptionHandler.java
  src/test/java/eightbit/moyeohaeng/domain/member/service/MemberServiceTest.java
Labels: ✨ feature

#27 [CHORE] application-test.yml
  src/test/resources/application-test.yml
Labels: ⚙️ chore

#31 [CHORE] application.yml에 CORS, JWT, logging 설정 추가
  .gitignore
  src/main/resources/application.yml
Labels: ⚙️ chore

#21 [CHORE] swagger 문서 설정
  .gitignore
  build.gradle
  src/main/java/eightbit/moyeohaeng/global/config/SwaggerConfig.java
  src/main/java/eightbit/moyeohaeng/global/team/controller/TeamApi.java
  src/main/java/eightbit/moyeohaeng/global/team/controller/TeamController.java
Labels: ⚙️ chore

#35 [FEATURE] application.yml .env import 추가 & swagger 문서 진입
  src/main/java/eightbit/moyeohaeng/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ♻️ refactor

#36 [FEATURE] global success 로직
  src/main/java/eightbit/moyeohaeng/domain/auth/common/exception/AuthErrorCode.java
  src/main/java/eightbit/moyeohaeng/domain/auth/common/exception/AuthException.java
  src/main/java/eightbit/moyeohaeng/domain/auth/common/success/AuthSuccessCode.java
  src/main/java/eightbit/moyeohaeng/domain/auth/controller/AuthController.java
  src/main/java/eightbit/moyeohaeng/domain/auth/service/AuthService.java
  src/main/java/eightbit/moyeohaeng/domain/member/common/exception/MemberErrorCode.java
  src/main/java/eightbit/moyeohaeng/domain/member/common/exception/MemberException.java
  src/main/java/eightbit/moyeohaeng/domain/member/common/success/MemberSuccessCode.java
  src/main/java/eightbit/moyeohaeng/domain/member/service/MemberService.java
  src/main/java/eightbit/moyeohaeng/global/exception/BaseException.java
  src/main/java/eightbit/moyeohaeng/global/exception/ErrorCode.java
  src/main/java/eightbit/moyeohaeng/global/exception/ErrorResponse.java
  src/main/java/eightbit/moyeohaeng/global/exception/GlobalErrorCode.java
  src/main/java/eightbit/moyeohaeng/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/eightbit/moyeohaeng/global/success/CommonSuccessCode.java
  src/main/java/eightbit/moyeohaeng/global/success/SuccessCode.java
  src/main/java/eightbit/moyeohaeng/global/success/SuccessResponse.java
  src/test/java/eightbit/moyeohaeng/domain/member/service/MemberServiceTest.java
  src/test/java/eightbit/moyeohaeng/global/exception/common/BaseExceptionTest.java
  src/test/java/eightbit/moyeohaeng/global/success/common/BaseSuccessResponseTest.java
Labels: ✨ feature

#32 [FEATURE] 장소블록 CRUD API 구현
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/controller/PlaceBlockController.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/controller/swagger/PlaceBlockApi.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/dto/request/PlaceBlockCreateRequest.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/dto/request/PlaceBlockUpdateRequest.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/dto/response/PlaceBlockResponse.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/entity/PlaceBlock.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/entity/PlaceBlockType.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/exception/PlaceBlockErrorCode.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/exception/PlaceBlockException.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/repository/PlaceBlockRepository.java
  src/main/java/eightbit/moyeohaeng/domain/project/placeblock/service/PlaceBlockService.java
  src/main/java/eightbit/moyeohaeng/global/dto/PageResponse.java
  src/test/java/eightbit/moyeohaeng/domain/project/placeblock/service/PlaceBlockServiceTest.java
Labels: ✨ feature

#39 [CHORE] Prometheus 설정
  build.gradle
  src/main/java/eightbit/moyeohaeng/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ⚙️ chore

#40 [CI/CD] 인프라 구축 및 배포 자동화
  .github/workflows/deploy-with-ecs.yml
  Dockerfile
  src/main/resources/application-prod.yml
Labels: 📦 ci/cd

#59 [FEATURE] 연관관계 매핑
  src/main/java/eightbit/moyeohaeng/domain/project/dto/request/PlaceBlockCreateRequest.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/response/PlaceBlockResponse.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/Pin.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/PlaceBlock.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/PlaceBlockComment.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/PlaceBlockLike.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/PlaceGroup.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/PlaceGroupBlock.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/Project.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/TimeBlock.java
  src/main/java/eightbit/moyeohaeng/domain/project/repository/PlaceBlockRepository.java
  src/main/java/eightbit/moyeohaeng/domain/project/repository/ProjectRepository.java
  src/main/java/eightbit/moyeohaeng/domain/project/service/PlaceBlockService.java
  src/main/java/eightbit/moyeohaeng/domain/team/entity/Team.java
  src/main/java/eightbit/moyeohaeng/domain/team/entity/TeamMember.java
  src/main/java/eightbit/moyeohaeng/domain/team/entity/TeamRole.java
  src/main/java/eightbit/moyeohaeng/global/team/entity/TeamRole.java
Labels: ✨ feature

#65 [CHORE] Redis 설정
  build.gradle
  compose.yml
  src/main/java/eightbit/moyeohaeng/global/config/RedisConfig.java
  src/main/resources/application-prod.yml
  src/test/java/eightbit/moyeohaeng/support/annotation/CleanUpRedis.java
  src/test/java/eightbit/moyeohaeng/support/container/TestContainers.java
  src/test/java/eightbit/moyeohaeng/support/extension/RedisCleanupExtension.java
Labels: ⚙️ chore

#66 [CHORE] QueryDSL 설정
  build.gradle
  src/main/java/eightbit/moyeohaeng/global/config/QueryDslConfig.java
Labels: ⚙️ chore
