Repository goorm-8bit/moyeohaeng-backend, pull requests merged in 2025-09, with the labels that each got.

#69 [FEATURE] Pin/PlaceBlock 관련 Interface + Controller + DTO 생성
  src/main/java/eightbit/moyeohaeng/domain/project/controller/PinController.java
  src/main/java/eightbit/moyeohaeng/domain/project/controller/PlaceBlockCommentController.java
  src/main/java/eightbit/moyeohaeng/domain/project/controller/PlaceBlockLikeController.java
  src/main/java/eightbit/moyeohaeng/domain/project/controller/swagger/PinApi.java
  src/main/java/eightbit/moyeohaeng/domain/project/controller/swagger/PlaceBlockCommentApi.java
  src/main/java/eightbit/moyeohaeng/domain/project/controller/swagger/PlaceBlockLikeApi.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/request/PinCreateRequest.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/request/PlaceBlockCommentCreateRequest.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/request/PlaceBlockCommentUpdateRequest.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/response/PinResponse.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/response/PlaceBlockCommentResponse.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/response/PlaceBlockCommentSummaryResponse.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/response/PlaceBlockLikeSummaryResponse.java
  src/main/java/eightbit/moyeohaeng/domain/project/entity/Pin.java
  src/main/java/eightbit/moyeohaeng/domain/project/service/PinService.java
  src/main/java/eightbit/moyeohaeng/domain/project/service/PlaceBlockCommentService.java
  src/main/java/eightbit/moyeohaeng/domain/project/service/PlaceBlockLikeService.java
Labels: ✨ feature

#77 [CHORE] open-in-view 비활성화 및 중복 로그 제거
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ⚙️ chore

#84 [FEATURE] 시간 블록 수정 API 구현
  src/main/java/eightbit/moyeohaeng/domain/itinerary/common/success/TimeBlockSuccessCode.java
  src/main/java/eightbit/moyeohaeng/domain/itinerary/controller/TimeBlockController.java
  src/main/java/eightbit/moyeohaeng/domain/itinerary/controller/swagger/TimeBlockApi.java
  src/main/java/eightbit/moyeohaeng/domain/itinerary/dto/request/TimeBlockUpdateRequest.java
  src/main/java/eightbit/moyeohaeng/domain/itinerary/entity/TimeBlock.java
  src/main/java/eightbit/moyeohaeng/domain/itinerary/repository/TimeBlockRepository.java
  src/main/java/eightbit/moyeohaeng/domain/itinerary/repository/TimeBlockRepositoryCustom.java
  src/main/java/eightbit/moyeohaeng/domain/itinerary/repository/TimeBlockRepositoryImpl.java
  src/main/java/eightbit/moyeohaeng/domain/itinerary/service/TimeBlockService.java
  src/test/java/eightbit/moyeohaeng/domain/itinerary/service/TimeBlockServiceTest.java
Labels: ✨ feature

#88 [CHORE] Swagger 설정 추가
  src/main/java/eightbit/moyeohaeng/domain/auth/dto/request/LoginRequest.java
  src/main/java/eightbit/moyeohaeng/domain/auth/dto/request/SignUpRequest.java
  src/main/java/eightbit/moyeohaeng/global/config/SwaggerConfig.java
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#81 [FEATURE] 장소 그룹 API 구현
  src/main/java/eightbit/moyeohaeng/domain/selection/common/exception/PlaceGroupErrorCode.java
  src/main/java/eightbit/moyeohaeng/domain/selection/common/exception/PlaceGroupException.java
  src/main/java/eightbit/moyeohaeng/domain/selection/common/success/PlaceGroupSuccessCode.java
  src/main/java/eightbit/moyeohaeng/domain/selection/controller/PlaceGroupController.java
  src/main/java/eightbit/moyeohaeng/domain/selection/controller/swagger/PlaceGroupApi.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/request/PlaceBlockToGroupsRequest.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/request/PlaceGroupRequest.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/request/PlaceGroupUpdateMemoRequest.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/response/PlaceGroupBlockResponse.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/response/PlaceGroupDeleteResponse.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/response/PlaceGroupResponse.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/response/PlaceGroupUpdateMemoResponse.java
  src/main/java/eightbit/moyeohaeng/domain/selection/entity/PlaceGroup.java
  src/main/java/eightbit/moyeohaeng/domain/selection/entity/PlaceGroupBlock.java
  src/main/java/eightbit/moyeohaeng/domain/selection/repository/PlaceBlockRepository.java
  src/main/java/eightbit/moyeohaeng/domain/selection/repository/PlaceGroupBlockRepository.java
  src/main/java/eightbit/moyeohaeng/domain/selection/repository/PlaceGroupRepository.java
  src/main/java/eightbit/moyeohaeng/domain/selection/repository/PlaceGroupRepositoryCustom.java
  src/main/java/eightbit/moyeohaeng/domain/selection/repository/PlaceGroupRepositoryImpl.java
  src/main/java/eightbit/moyeohaeng/domain/selection/service/PlaceGroupService.java
Labels: ✨ feature

#92 [FEATURE] 장소블록 코멘트 API 구현
  src/main/java/eightbit/moyeohaeng/domain/selection/common/exception/PlaceBlockCommentErrorCode.java
  src/main/java/eightbit/moyeohaeng/domain/selection/common/exception/PlaceBlockCommentException.java
  src/main/java/eightbit/moyeohaeng/domain/selection/common/success/PlaceBlockCommentSuccessCode.java
  src/main/java/eightbit/moyeohaeng/domain/selection/controller/PlaceBlockCommentController.java
  src/main/java/eightbit/moyeohaeng/domain/selection/controller/swagger/PlaceBlockCommentApi.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/response/PlaceBlockCommentDeleteResponse.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/response/PlaceBlockCommentResponse.java
  src/main/java/eightbit/moyeohaeng/domain/selection/entity/PlaceBlockComment.java
  src/main/java/eightbit/moyeohaeng/domain/selection/repository/PlaceBlockCommentRepository.java
  src/main/java/eightbit/moyeohaeng/domain/selection/service/PlaceBlockCommentService.java
Labels: ✨ feature

#91 [FEATURE] 장소블록 좋아요 API 구현
  src/main/java/eightbit/moyeohaeng/domain/map/dto/request/PinCreateRequest.java
  src/main/java/eightbit/moyeohaeng/domain/map/service/PinService.java
  src/main/java/eightbit/moyeohaeng/domain/selection/common/success/PlaceBlockLikeSuccessCode.java
  src/main/java/eightbit/moyeohaeng/domain/selection/controller/PlaceBlockLikeController.java
  src/main/java/eightbit/moyeohaeng/domain/selection/controller/swagger/PlaceBlockLikeApi.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/response/PlaceBlockLikeResponse.java
  src/main/java/eightbit/moyeohaeng/domain/selection/dto/response/PlaceBlockLikeSummaryResponse.java
  src/main/java/eightbit/moyeohaeng/domain/selection/entity/PlaceBlockLike.java
  src/main/java/eightbit/moyeohaeng/domain/selection/repository/PlaceBlockLikeRepository.java
  src/main/java/eightbit/moyeohaeng/domain/selection/repository/PlaceBlockRepository.java
  src/main/java/eightbit/moyeohaeng/domain/selection/service/PlaceBlockLikeService.java
Labels: ✨ feature

#111 [FEATURE] Project response에 id 추가
  src/main/java/eightbit/moyeohaeng/domain/project/dto/ProjectDto.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/request/ProjectCreateRequest.java
Labels: ✨ feature

#113 [RELEASE] 2차 - Project response에 id 추가
  src/main/java/eightbit/moyeohaeng/domain/project/dto/ProjectDto.java
  src/main/java/eightbit/moyeohaeng/domain/project/dto/request/ProjectCreateRequest.java
Labels: 🚀 release

#129 [RELEASE] 5차 - 누락된 어노테이션 추가
  src/main/java/eightbit/moyeohaeng/domain/itinerary/service/TimeBlockService.java
Labels: 🚀 release
